### ISSUE TITLE
Enable people to log in, create favourites and add their own tags

### ISSUE THREAD

**Issue by gilliankerr** [LogicalOutcomes/indicatorregistry#9]
@gilliankerr commented on [Fri Nov 04 2016](https://github.com/LogicalOutcomes/aristotle-NGO/issues/23)

**Comment by gilliankerr** [comment]
Actually, this is probably several different issues. Start with the 'log in' button on home page to enable current work flow for users.

**Comment by rafen** [comment]
@gilliankerr I deployed the changes to allow users to login. I think we can close this issue and add a new one for the other tasks
